---
name: Release

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: romain-cambonie/serenity-workflows/.github/workflows/_build-and-upload-artifact.reusable.yml@master
    with:
      out-dir: lib

  validation:
    uses: romain-cambonie/serenity-workflows/.github/workflows/_validation-matrix.reusable.yml@master
    with:
      commands-as-comma-separated-string: 'lint,prettier.check,test'

  publish:
    name: Publish package on npm
    runs-on: ubuntu-latest
    needs:
      - build
      - validation

    steps:
      - name: Checkout timetable-to-osm-opening-hours repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: bundle

      # Using a symbolic link because there is no base option to have a config path with semantic-release as of 2022-08-31
      - name: Link the semantic release config and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          ln -s .tooling/.semantic-release/.semantic-release.config.cjs release.config.cjs
          ln -s .tooling/.semantic-release/.npmignore .npmignore
          npx semantic-release
